language: python
sudo: false
branches:
only:
  - master
python:
  - 3.5
  - 3.6

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p ./miniconda
  - export PATH=`pwd`/miniconda/bin:$PATH
  - conda update --yes conda
  - conda config --add channels conda-forge
  - conda config --set channel_priority strict
  - conda create -y -q -n test-env python=$TRAVIS_PYTHON_VERSION pip
  - source activate test-env
  - conda install --yes numpy geopandas matplotlib seaborn ipywidgets bokeh
  - conda list
  - conda info -a

install:
  - pip install -r requirements.txt
  - pip install nose coverage coveralls
  # Now install splot (don't use 'pip install .', we'll run out of space)
  - python setup.py sdist
  - cd dist && pip install splot-*.tar.gz && cd ..
  # We need the Agg backend to use Matplotlib on TravisCI, otherwise
  # we get an error "DISPLAY variable not set"
  - cp utils/matplotlibrc .


script:
  - nosetests splot --with-doctest --with-coverage --cover-package=splot;
#  - cd notebooks
#  - make test

notifications:
    email:
        recipients:
            - sjsrey@gmail.com
        on_change: always
        on_failure: always

after_success:
  - coveralls
